// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAotjG2ZV--E_DIAR9GIg3zeiQ9YWAcMg',
    appId: '1:199561142413:web:dd0b60f78f14ef229c82c4',
    messagingSenderId: '199561142413',
    projectId: 'first-app-f2d4c',
    authDomain: 'first-app-f2d4c.firebaseapp.com',
    storageBucket: 'first-app-f2d4c.firebasestorage.app',
    measurementId: 'G-45FR4KSFT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV7Vz2B3VUr72qDK79bdBME8J39VOUqmQ',
    appId: '1:199561142413:android:014ecb69b60a1a369c82c4',
    messagingSenderId: '199561142413',
    projectId: 'first-app-f2d4c',
    storageBucket: 'first-app-f2d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXwJRg9WqWnHgmsqRD6esawwmJKUTN0A',
    appId: '1:199561142413:ios:af8a47f2ae040a589c82c4',
    messagingSenderId: '199561142413',
    projectId: 'first-app-f2d4c',
    storageBucket: 'first-app-f2d4c.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoXwJRg9WqWnHgmsqRD6esawwmJKUTN0A',
    appId: '1:199561142413:ios:af8a47f2ae040a589c82c4',
    messagingSenderId: '199561142413',
    projectId: 'first-app-f2d4c',
    storageBucket: 'first-app-f2d4c.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAotjG2ZV--E_DIAR9GIg3zeiQ9YWAcMg',
    appId: '1:199561142413:web:82f67d0e69b5cbd99c82c4',
    messagingSenderId: '199561142413',
    projectId: 'first-app-f2d4c',
    authDomain: 'first-app-f2d4c.firebaseapp.com',
    storageBucket: 'first-app-f2d4c.firebasestorage.app',
    measurementId: 'G-VZX8NR2JKL',
  );
}
